### PR TITLE
Initial script to build selected model and save to excel

### PR DESCRIPTION
**Pull request by bl-young**

### CODE REVIEW

**Comment by WesIngwersen** [comment]
Files required for build not on Data Commons

Water_state_2015_m1_v2.0.0_372aab5.parquet (used in 2012-2018 method specs)

missing metadata:
FEDEFL_Inventory_v1.0.0_5555779_metadata.json
TRACI_2.1_v1.0.0_5555779_metadata.json

**Comment by WesIngwersen** [comment]
Closing for now to reassess options

**Comment by bl-young** [comment]
I believe the water FBS is an oversight. All the water methods should be the same as it's a single year. We updated 2019-2020 but not the other years. 

I can get the metadata files added.

**Comment by bl-young** [comment]
FYI those files have been added to data commons

**Pull request closed without merging**
